services:
  - type: web
    name: mtaani-connect
    env: python
    buildCommand: ./build.sh
    startCommand: gunicorn mtaani_project.wsgi:application
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.0
      - key: DEBUG
        value: "False"
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
      - key: DATABASE_URL
        sync: false # Set this in the Render dashboard or provide it here
      - key: ALLOWED_HOSTS
        value: .onrender.com
      - key: CSRF_TRUSTED_ORIGINS
        value: https://*.onrender.com
